#pragma checksum "..\..\..\..\View\AddNurse.xaml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "4B6F0735E7189B33F7A0698AC2AC5BB0EE9A9B16"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Controls.Ribbon;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;
using VistaLife.View;


namespace VistaLife.View {
    
    
    /// <summary>
    /// AddNurse
    /// </summary>
    public partial class AddNurse : System.Windows.Window, System.Windows.Markup.IComponentConnector {
        
        
        #line 65 "..\..\..\..\View\AddNurse.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btnMinimize;
        
        #line default
        #line hidden
        
        
        #line 99 "..\..\..\..\View\AddNurse.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btnMaximize;
        
        #line default
        #line hidden
        
        
        #line 132 "..\..\..\..\View\AddNurse.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btnClose;
        
        #line default
        #line hidden
        
        
        #line 167 "..\..\..\..\View\AddNurse.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.StackPanel loginStackPanel;
        
        #line default
        #line hidden
        
        
        #line 191 "..\..\..\..\View\AddNurse.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox Title;
        
        #line default
        #line hidden
        
        
        #line 192 "..\..\..\..\View\AddNurse.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox txtNName;
        
        #line default
        #line hidden
        
        
        #line 193 "..\..\..\..\View\AddNurse.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox txtNAge;
        
        #line default
        #line hidden
        
        
        #line 194 "..\..\..\..\View\AddNurse.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox txtNAddress;
        
        #line default
        #line hidden
        
        
        #line 195 "..\..\..\..\View\AddNurse.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ComboBox comboboxWard;
        
        #line default
        #line hidden
        
        
        #line 196 "..\..\..\..\View\AddNurse.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox txtExperience;
        
        #line default
        #line hidden
        
        
        #line 197 "..\..\..\..\View\AddNurse.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label lbl_NName;
        
        #line default
        #line hidden
        
        
        #line 198 "..\..\..\..\View\AddNurse.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label lbl_nAge;
        
        #line default
        #line hidden
        
        
        #line 199 "..\..\..\..\View\AddNurse.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label lbl_NAddress;
        
        #line default
        #line hidden
        
        
        #line 200 "..\..\..\..\View\AddNurse.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label lbl_ward;
        
        #line default
        #line hidden
        
        
        #line 201 "..\..\..\..\View\AddNurse.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label lbl_Experience;
        
        #line default
        #line hidden
        
        
        #line 203 "..\..\..\..\View\AddNurse.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btnSave;
        
        #line default
        #line hidden
        
        
        #line 204 "..\..\..\..\View\AddNurse.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btnClear;
        
        #line default
        #line hidden
        
        
        #line 209 "..\..\..\..\View\AddNurse.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Grid Grid_Menu;
        
        #line default
        #line hidden
        
        
        #line 219 "..\..\..\..\View\AddNurse.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button back;
        
        #line default
        #line hidden
        
        
        #line 225 "..\..\..\..\View\AddNurse.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btnAddpatient;
        
        #line default
        #line hidden
        
        
        #line 230 "..\..\..\..\View\AddNurse.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button BtnStaffDetails;
        
        #line default
        #line hidden
        
        
        #line 235 "..\..\..\..\View\AddNurse.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button BtnPDetails;
        
        #line default
        #line hidden
        
        
        #line 240 "..\..\..\..\View\AddNurse.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btnChannel;
        
        #line default
        #line hidden
        
        
        #line 245 "..\..\..\..\View\AddNurse.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btnLogout;
        
        #line default
        #line hidden
        
        
        #line 249 "..\..\..\..\View\AddNurse.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label lbl_LogOut;
        
        #line default
        #line hidden
        
        
        #line 251 "..\..\..\..\View\AddNurse.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label lbl_Addmit;
        
        #line default
        #line hidden
        
        
        #line 252 "..\..\..\..\View\AddNurse.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label lbl_Channel;
        
        #line default
        #line hidden
        
        
        #line 253 "..\..\..\..\View\AddNurse.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label lbl_ViewPatient;
        
        #line default
        #line hidden
        
        
        #line 254 "..\..\..\..\View\AddNurse.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label lbl_ViewStaff;
        
        #line default
        #line hidden
        
        
        #line 261 "..\..\..\..\View\AddNurse.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label lbl_N_Type;
        
        #line default
        #line hidden
        
        
        #line 272 "..\..\..\..\View\AddNurse.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label lbl_Addmit_Copy;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "8.0.0.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/VistaLife;component/view/addnurse.xaml", System.UriKind.Relative);
            
            #line 1 "..\..\..\..\View\AddNurse.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "8.0.0.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            
            #line 14 "..\..\..\..\View\AddNurse.xaml"
            ((VistaLife.View.AddNurse)(target)).MouseDown += new System.Windows.Input.MouseButtonEventHandler(this.Window_MouseDown);
            
            #line default
            #line hidden
            return;
            case 2:
            this.btnMinimize = ((System.Windows.Controls.Button)(target));
            
            #line 74 "..\..\..\..\View\AddNurse.xaml"
            this.btnMinimize.Click += new System.Windows.RoutedEventHandler(this.btnMinimize_Click);
            
            #line default
            #line hidden
            return;
            case 3:
            this.btnMaximize = ((System.Windows.Controls.Button)(target));
            
            #line 106 "..\..\..\..\View\AddNurse.xaml"
            this.btnMaximize.Click += new System.Windows.RoutedEventHandler(this.btnMaximize_Click);
            
            #line default
            #line hidden
            return;
            case 4:
            this.btnClose = ((System.Windows.Controls.Button)(target));
            
            #line 141 "..\..\..\..\View\AddNurse.xaml"
            this.btnClose.Click += new System.Windows.RoutedEventHandler(this.btnClose_Click);
            
            #line default
            #line hidden
            return;
            case 5:
            this.loginStackPanel = ((System.Windows.Controls.StackPanel)(target));
            return;
            case 6:
            this.Title = ((System.Windows.Controls.TextBox)(target));
            return;
            case 7:
            this.txtNName = ((System.Windows.Controls.TextBox)(target));
            return;
            case 8:
            this.txtNAge = ((System.Windows.Controls.TextBox)(target));
            return;
            case 9:
            this.txtNAddress = ((System.Windows.Controls.TextBox)(target));
            return;
            case 10:
            this.comboboxWard = ((System.Windows.Controls.ComboBox)(target));
            return;
            case 11:
            this.txtExperience = ((System.Windows.Controls.TextBox)(target));
            return;
            case 12:
            this.lbl_NName = ((System.Windows.Controls.Label)(target));
            return;
            case 13:
            this.lbl_nAge = ((System.Windows.Controls.Label)(target));
            return;
            case 14:
            this.lbl_NAddress = ((System.Windows.Controls.Label)(target));
            return;
            case 15:
            this.lbl_ward = ((System.Windows.Controls.Label)(target));
            return;
            case 16:
            this.lbl_Experience = ((System.Windows.Controls.Label)(target));
            return;
            case 17:
            this.btnSave = ((System.Windows.Controls.Button)(target));
            
            #line 203 "..\..\..\..\View\AddNurse.xaml"
            this.btnSave.Click += new System.Windows.RoutedEventHandler(this.btnSave_Click);
            
            #line default
            #line hidden
            return;
            case 18:
            this.btnClear = ((System.Windows.Controls.Button)(target));
            
            #line 204 "..\..\..\..\View\AddNurse.xaml"
            this.btnClear.Click += new System.Windows.RoutedEventHandler(this.btnClear_Click);
            
            #line default
            #line hidden
            return;
            case 19:
            this.Grid_Menu = ((System.Windows.Controls.Grid)(target));
            return;
            case 20:
            this.back = ((System.Windows.Controls.Button)(target));
            
            #line 219 "..\..\..\..\View\AddNurse.xaml"
            this.back.Click += new System.Windows.RoutedEventHandler(this.back_Click);
            
            #line default
            #line hidden
            return;
            case 21:
            this.btnAddpatient = ((System.Windows.Controls.Button)(target));
            
            #line 225 "..\..\..\..\View\AddNurse.xaml"
            this.btnAddpatient.Click += new System.Windows.RoutedEventHandler(this.btnAddpatient_Click);
            
            #line default
            #line hidden
            return;
            case 22:
            this.BtnStaffDetails = ((System.Windows.Controls.Button)(target));
            
            #line 230 "..\..\..\..\View\AddNurse.xaml"
            this.BtnStaffDetails.Click += new System.Windows.RoutedEventHandler(this.BtnStaffDetails_Click);
            
            #line default
            #line hidden
            return;
            case 23:
            this.BtnPDetails = ((System.Windows.Controls.Button)(target));
            
            #line 235 "..\..\..\..\View\AddNurse.xaml"
            this.BtnPDetails.Click += new System.Windows.RoutedEventHandler(this.BtnPDetails_Click);
            
            #line default
            #line hidden
            return;
            case 24:
            this.btnChannel = ((System.Windows.Controls.Button)(target));
            
            #line 240 "..\..\..\..\View\AddNurse.xaml"
            this.btnChannel.Click += new System.Windows.RoutedEventHandler(this.btnChannel_Click);
            
            #line default
            #line hidden
            return;
            case 25:
            this.btnLogout = ((System.Windows.Controls.Button)(target));
            
            #line 245 "..\..\..\..\View\AddNurse.xaml"
            this.btnLogout.Click += new System.Windows.RoutedEventHandler(this.btnLogout_Click);
            
            #line default
            #line hidden
            return;
            case 26:
            this.lbl_LogOut = ((System.Windows.Controls.Label)(target));
            return;
            case 27:
            this.lbl_Addmit = ((System.Windows.Controls.Label)(target));
            return;
            case 28:
            this.lbl_Channel = ((System.Windows.Controls.Label)(target));
            return;
            case 29:
            this.lbl_ViewPatient = ((System.Windows.Controls.Label)(target));
            return;
            case 30:
            this.lbl_ViewStaff = ((System.Windows.Controls.Label)(target));
            return;
            case 31:
            this.lbl_N_Type = ((System.Windows.Controls.Label)(target));
            return;
            case 32:
            this.lbl_Addmit_Copy = ((System.Windows.Controls.Label)(target));
            return;
            }
            this._contentLoaded = true;
        }
    }
}

