#pragma checksum "..\..\..\..\View\AddStaff.xaml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "CF0CA0116E90DE8A57AB15BB9458744945923B74"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Controls.Ribbon;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;
using VistaLife.View;


namespace VistaLife.View {
    
    
    /// <summary>
    /// AddStaff
    /// </summary>
    public partial class AddStaff : System.Windows.Window, System.Windows.Markup.IComponentConnector {
        
        
        #line 65 "..\..\..\..\View\AddStaff.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btnMinimize;
        
        #line default
        #line hidden
        
        
        #line 99 "..\..\..\..\View\AddStaff.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btnMaximize;
        
        #line default
        #line hidden
        
        
        #line 132 "..\..\..\..\View\AddStaff.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btnClose;
        
        #line default
        #line hidden
        
        
        #line 167 "..\..\..\..\View\AddStaff.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.StackPanel loginStackPanel;
        
        #line default
        #line hidden
        
        
        #line 187 "..\..\..\..\View\AddStaff.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox Title;
        
        #line default
        #line hidden
        
        
        #line 188 "..\..\..\..\View\AddStaff.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox txtDName;
        
        #line default
        #line hidden
        
        
        #line 189 "..\..\..\..\View\AddStaff.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox txtDAge;
        
        #line default
        #line hidden
        
        
        #line 190 "..\..\..\..\View\AddStaff.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox txtAddress;
        
        #line default
        #line hidden
        
        
        #line 191 "..\..\..\..\View\AddStaff.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ComboBox txtDType;
        
        #line default
        #line hidden
        
        
        #line 195 "..\..\..\..\View\AddStaff.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ComboBox txtSpeciality;
        
        #line default
        #line hidden
        
        
        #line 217 "..\..\..\..\View\AddStaff.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox txtExperience;
        
        #line default
        #line hidden
        
        
        #line 220 "..\..\..\..\View\AddStaff.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label lbl_DName;
        
        #line default
        #line hidden
        
        
        #line 221 "..\..\..\..\View\AddStaff.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label lbl_DAge;
        
        #line default
        #line hidden
        
        
        #line 222 "..\..\..\..\View\AddStaff.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label lbl_DAddress;
        
        #line default
        #line hidden
        
        
        #line 223 "..\..\..\..\View\AddStaff.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label lbl_Doctor_Type;
        
        #line default
        #line hidden
        
        
        #line 224 "..\..\..\..\View\AddStaff.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label lbl_Speciality;
        
        #line default
        #line hidden
        
        
        #line 225 "..\..\..\..\View\AddStaff.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label lbl_Experience;
        
        #line default
        #line hidden
        
        
        #line 231 "..\..\..\..\View\AddStaff.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btnSave;
        
        #line default
        #line hidden
        
        
        #line 232 "..\..\..\..\View\AddStaff.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btnClear;
        
        #line default
        #line hidden
        
        
        #line 237 "..\..\..\..\View\AddStaff.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Grid Grid_Menu;
        
        #line default
        #line hidden
        
        
        #line 247 "..\..\..\..\View\AddStaff.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button back;
        
        #line default
        #line hidden
        
        
        #line 253 "..\..\..\..\View\AddStaff.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btnAddpatient;
        
        #line default
        #line hidden
        
        
        #line 258 "..\..\..\..\View\AddStaff.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button BtnStaffDetails;
        
        #line default
        #line hidden
        
        
        #line 263 "..\..\..\..\View\AddStaff.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button BtnPDetails;
        
        #line default
        #line hidden
        
        
        #line 268 "..\..\..\..\View\AddStaff.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btnChannel;
        
        #line default
        #line hidden
        
        
        #line 273 "..\..\..\..\View\AddStaff.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btnLogout;
        
        #line default
        #line hidden
        
        
        #line 277 "..\..\..\..\View\AddStaff.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label lbl_LogOut;
        
        #line default
        #line hidden
        
        
        #line 279 "..\..\..\..\View\AddStaff.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label lbl_Addmit;
        
        #line default
        #line hidden
        
        
        #line 280 "..\..\..\..\View\AddStaff.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label lbl_Channel;
        
        #line default
        #line hidden
        
        
        #line 281 "..\..\..\..\View\AddStaff.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label lbl_ViewPatient;
        
        #line default
        #line hidden
        
        
        #line 282 "..\..\..\..\View\AddStaff.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label lbl_ViewStaff;
        
        #line default
        #line hidden
        
        
        #line 284 "..\..\..\..\View\AddStaff.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label lbl_Addmit_Copy;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "8.0.1.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/VistaLife;V1.0.0.0;component/view/addstaff.xaml", System.UriKind.Relative);
            
            #line 1 "..\..\..\..\View\AddStaff.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "8.0.1.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            
            #line 14 "..\..\..\..\View\AddStaff.xaml"
            ((VistaLife.View.AddStaff)(target)).MouseDown += new System.Windows.Input.MouseButtonEventHandler(this.Window_MouseDown);
            
            #line default
            #line hidden
            return;
            case 2:
            this.btnMinimize = ((System.Windows.Controls.Button)(target));
            
            #line 74 "..\..\..\..\View\AddStaff.xaml"
            this.btnMinimize.Click += new System.Windows.RoutedEventHandler(this.btnMinimize_Click);
            
            #line default
            #line hidden
            return;
            case 3:
            this.btnMaximize = ((System.Windows.Controls.Button)(target));
            
            #line 106 "..\..\..\..\View\AddStaff.xaml"
            this.btnMaximize.Click += new System.Windows.RoutedEventHandler(this.btnMaximize_Click);
            
            #line default
            #line hidden
            return;
            case 4:
            this.btnClose = ((System.Windows.Controls.Button)(target));
            
            #line 141 "..\..\..\..\View\AddStaff.xaml"
            this.btnClose.Click += new System.Windows.RoutedEventHandler(this.btnClose_Click);
            
            #line default
            #line hidden
            return;
            case 5:
            this.loginStackPanel = ((System.Windows.Controls.StackPanel)(target));
            return;
            case 6:
            this.Title = ((System.Windows.Controls.TextBox)(target));
            return;
            case 7:
            this.txtDName = ((System.Windows.Controls.TextBox)(target));
            return;
            case 8:
            this.txtDAge = ((System.Windows.Controls.TextBox)(target));
            return;
            case 9:
            this.txtAddress = ((System.Windows.Controls.TextBox)(target));
            return;
            case 10:
            this.txtDType = ((System.Windows.Controls.ComboBox)(target));
            return;
            case 11:
            this.txtSpeciality = ((System.Windows.Controls.ComboBox)(target));
            return;
            case 12:
            this.txtExperience = ((System.Windows.Controls.TextBox)(target));
            return;
            case 13:
            this.lbl_DName = ((System.Windows.Controls.Label)(target));
            return;
            case 14:
            this.lbl_DAge = ((System.Windows.Controls.Label)(target));
            return;
            case 15:
            this.lbl_DAddress = ((System.Windows.Controls.Label)(target));
            return;
            case 16:
            this.lbl_Doctor_Type = ((System.Windows.Controls.Label)(target));
            return;
            case 17:
            this.lbl_Speciality = ((System.Windows.Controls.Label)(target));
            return;
            case 18:
            this.lbl_Experience = ((System.Windows.Controls.Label)(target));
            return;
            case 19:
            this.btnSave = ((System.Windows.Controls.Button)(target));
            
            #line 231 "..\..\..\..\View\AddStaff.xaml"
            this.btnSave.Click += new System.Windows.RoutedEventHandler(this.btnSave_Click);
            
            #line default
            #line hidden
            return;
            case 20:
            this.btnClear = ((System.Windows.Controls.Button)(target));
            
            #line 232 "..\..\..\..\View\AddStaff.xaml"
            this.btnClear.Click += new System.Windows.RoutedEventHandler(this.btnClear_Click);
            
            #line default
            #line hidden
            return;
            case 21:
            this.Grid_Menu = ((System.Windows.Controls.Grid)(target));
            return;
            case 22:
            this.back = ((System.Windows.Controls.Button)(target));
            
            #line 247 "..\..\..\..\View\AddStaff.xaml"
            this.back.Click += new System.Windows.RoutedEventHandler(this.back_Click);
            
            #line default
            #line hidden
            return;
            case 23:
            this.btnAddpatient = ((System.Windows.Controls.Button)(target));
            
            #line 253 "..\..\..\..\View\AddStaff.xaml"
            this.btnAddpatient.Click += new System.Windows.RoutedEventHandler(this.btnAddpatient_Click);
            
            #line default
            #line hidden
            return;
            case 24:
            this.BtnStaffDetails = ((System.Windows.Controls.Button)(target));
            
            #line 258 "..\..\..\..\View\AddStaff.xaml"
            this.BtnStaffDetails.Click += new System.Windows.RoutedEventHandler(this.BtnStaffDetails_Click);
            
            #line default
            #line hidden
            return;
            case 25:
            this.BtnPDetails = ((System.Windows.Controls.Button)(target));
            
            #line 263 "..\..\..\..\View\AddStaff.xaml"
            this.BtnPDetails.Click += new System.Windows.RoutedEventHandler(this.BtnPDetails_Click);
            
            #line default
            #line hidden
            return;
            case 26:
            this.btnChannel = ((System.Windows.Controls.Button)(target));
            
            #line 268 "..\..\..\..\View\AddStaff.xaml"
            this.btnChannel.Click += new System.Windows.RoutedEventHandler(this.btnChannel_Click);
            
            #line default
            #line hidden
            return;
            case 27:
            this.btnLogout = ((System.Windows.Controls.Button)(target));
            
            #line 273 "..\..\..\..\View\AddStaff.xaml"
            this.btnLogout.Click += new System.Windows.RoutedEventHandler(this.btnLogout_Click);
            
            #line default
            #line hidden
            return;
            case 28:
            this.lbl_LogOut = ((System.Windows.Controls.Label)(target));
            return;
            case 29:
            this.lbl_Addmit = ((System.Windows.Controls.Label)(target));
            return;
            case 30:
            this.lbl_Channel = ((System.Windows.Controls.Label)(target));
            return;
            case 31:
            this.lbl_ViewPatient = ((System.Windows.Controls.Label)(target));
            return;
            case 32:
            this.lbl_ViewStaff = ((System.Windows.Controls.Label)(target));
            return;
            case 33:
            this.lbl_Addmit_Copy = ((System.Windows.Controls.Label)(target));
            return;
            }
            this._contentLoaded = true;
        }
    }
}

