#pragma checksum "..\..\..\..\View\Bill.xaml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "75F3CAF5069004573737BB64C62881D98249AB8B"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Controls.Ribbon;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;
using VistaLife.View;


namespace VistaLife.View {
    
    
    /// <summary>
    /// Bill
    /// </summary>
    public partial class Bill : System.Windows.Window, System.Windows.Markup.IComponentConnector {
        
        
        #line 65 "..\..\..\..\View\Bill.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btnMinimize;
        
        #line default
        #line hidden
        
        
        #line 99 "..\..\..\..\View\Bill.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btnMaximize;
        
        #line default
        #line hidden
        
        
        #line 132 "..\..\..\..\View\Bill.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btnClose;
        
        #line default
        #line hidden
        
        
        #line 167 "..\..\..\..\View\Bill.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.StackPanel loginStackPanel;
        
        #line default
        #line hidden
        
        
        #line 187 "..\..\..\..\View\Bill.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox txtPName;
        
        #line default
        #line hidden
        
        
        #line 190 "..\..\..\..\View\Bill.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label lbl_PID;
        
        #line default
        #line hidden
        
        
        #line 191 "..\..\..\..\View\Bill.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label lbl_ExtraServises;
        
        #line default
        #line hidden
        
        
        #line 192 "..\..\..\..\View\Bill.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label TotaleBill;
        
        #line default
        #line hidden
        
        
        #line 193 "..\..\..\..\View\Bill.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label TotBillShow;
        
        #line default
        #line hidden
        
        
        #line 201 "..\..\..\..\View\Bill.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox chek_blood;
        
        #line default
        #line hidden
        
        
        #line 202 "..\..\..\..\View\Bill.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox chek_Xray;
        
        #line default
        #line hidden
        
        
        #line 203 "..\..\..\..\View\Bill.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox chek_CTscan;
        
        #line default
        #line hidden
        
        
        #line 204 "..\..\..\..\View\Bill.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox chek_ECG;
        
        #line default
        #line hidden
        
        
        #line 205 "..\..\..\..\View\Bill.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox chek_MRIscan;
        
        #line default
        #line hidden
        
        
        #line 206 "..\..\..\..\View\Bill.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox chek_EEG;
        
        #line default
        #line hidden
        
        
        #line 207 "..\..\..\..\View\Bill.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox chek_Eco;
        
        #line default
        #line hidden
        
        
        #line 208 "..\..\..\..\View\Bill.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox chek_Endoscopy;
        
        #line default
        #line hidden
        
        
        #line 211 "..\..\..\..\View\Bill.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btnCalculate;
        
        #line default
        #line hidden
        
        
        #line 212 "..\..\..\..\View\Bill.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btnClear;
        
        #line default
        #line hidden
        
        
        #line 220 "..\..\..\..\View\Bill.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Grid Grid_Menu;
        
        #line default
        #line hidden
        
        
        #line 230 "..\..\..\..\View\Bill.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button back;
        
        #line default
        #line hidden
        
        
        #line 236 "..\..\..\..\View\Bill.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btnAddpatient;
        
        #line default
        #line hidden
        
        
        #line 241 "..\..\..\..\View\Bill.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button BtnStaffDetails;
        
        #line default
        #line hidden
        
        
        #line 246 "..\..\..\..\View\Bill.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button BtnPDetails;
        
        #line default
        #line hidden
        
        
        #line 251 "..\..\..\..\View\Bill.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btnChannel;
        
        #line default
        #line hidden
        
        
        #line 256 "..\..\..\..\View\Bill.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btnLogout;
        
        #line default
        #line hidden
        
        
        #line 260 "..\..\..\..\View\Bill.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label lbl_LogOut;
        
        #line default
        #line hidden
        
        
        #line 262 "..\..\..\..\View\Bill.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label lbl_Addmit;
        
        #line default
        #line hidden
        
        
        #line 263 "..\..\..\..\View\Bill.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label lbl_Channel;
        
        #line default
        #line hidden
        
        
        #line 264 "..\..\..\..\View\Bill.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label lbl_ViewPatient;
        
        #line default
        #line hidden
        
        
        #line 265 "..\..\..\..\View\Bill.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label lbl_ViewStaff;
        
        #line default
        #line hidden
        
        
        #line 268 "..\..\..\..\View\Bill.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label lbl_Addmit_Copy;
        
        #line default
        #line hidden
        
        
        #line 273 "..\..\..\..\View\Bill.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label lbldischargedate;
        
        #line default
        #line hidden
        
        
        #line 275 "..\..\..\..\View\Bill.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Calendar calander;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "8.0.1.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/VistaLife;V1.0.0.0;component/view/bill.xaml", System.UriKind.Relative);
            
            #line 1 "..\..\..\..\View\Bill.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "8.0.1.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            
            #line 14 "..\..\..\..\View\Bill.xaml"
            ((VistaLife.View.Bill)(target)).MouseDown += new System.Windows.Input.MouseButtonEventHandler(this.Window_MouseDown);
            
            #line default
            #line hidden
            return;
            case 2:
            this.btnMinimize = ((System.Windows.Controls.Button)(target));
            
            #line 74 "..\..\..\..\View\Bill.xaml"
            this.btnMinimize.Click += new System.Windows.RoutedEventHandler(this.btnMinimize_Click);
            
            #line default
            #line hidden
            return;
            case 3:
            this.btnMaximize = ((System.Windows.Controls.Button)(target));
            
            #line 106 "..\..\..\..\View\Bill.xaml"
            this.btnMaximize.Click += new System.Windows.RoutedEventHandler(this.btnMaximize_Click);
            
            #line default
            #line hidden
            return;
            case 4:
            this.btnClose = ((System.Windows.Controls.Button)(target));
            
            #line 141 "..\..\..\..\View\Bill.xaml"
            this.btnClose.Click += new System.Windows.RoutedEventHandler(this.btnClose_Click);
            
            #line default
            #line hidden
            return;
            case 5:
            this.loginStackPanel = ((System.Windows.Controls.StackPanel)(target));
            return;
            case 6:
            this.txtPName = ((System.Windows.Controls.TextBox)(target));
            return;
            case 7:
            this.lbl_PID = ((System.Windows.Controls.Label)(target));
            return;
            case 8:
            this.lbl_ExtraServises = ((System.Windows.Controls.Label)(target));
            return;
            case 9:
            this.TotaleBill = ((System.Windows.Controls.Label)(target));
            return;
            case 10:
            this.TotBillShow = ((System.Windows.Controls.Label)(target));
            return;
            case 11:
            this.chek_blood = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 12:
            this.chek_Xray = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 13:
            this.chek_CTscan = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 14:
            this.chek_ECG = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 15:
            this.chek_MRIscan = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 16:
            this.chek_EEG = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 17:
            this.chek_Eco = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 18:
            this.chek_Endoscopy = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 19:
            this.btnCalculate = ((System.Windows.Controls.Button)(target));
            return;
            case 20:
            this.btnClear = ((System.Windows.Controls.Button)(target));
            
            #line 212 "..\..\..\..\View\Bill.xaml"
            this.btnClear.Click += new System.Windows.RoutedEventHandler(this.btnClear_Click);
            
            #line default
            #line hidden
            return;
            case 21:
            this.Grid_Menu = ((System.Windows.Controls.Grid)(target));
            return;
            case 22:
            this.back = ((System.Windows.Controls.Button)(target));
            
            #line 230 "..\..\..\..\View\Bill.xaml"
            this.back.Click += new System.Windows.RoutedEventHandler(this.back_Click);
            
            #line default
            #line hidden
            return;
            case 23:
            this.btnAddpatient = ((System.Windows.Controls.Button)(target));
            
            #line 236 "..\..\..\..\View\Bill.xaml"
            this.btnAddpatient.Click += new System.Windows.RoutedEventHandler(this.btnAddpatient_Click);
            
            #line default
            #line hidden
            return;
            case 24:
            this.BtnStaffDetails = ((System.Windows.Controls.Button)(target));
            
            #line 241 "..\..\..\..\View\Bill.xaml"
            this.BtnStaffDetails.Click += new System.Windows.RoutedEventHandler(this.BtnStaffDetails_Click);
            
            #line default
            #line hidden
            return;
            case 25:
            this.BtnPDetails = ((System.Windows.Controls.Button)(target));
            
            #line 246 "..\..\..\..\View\Bill.xaml"
            this.BtnPDetails.Click += new System.Windows.RoutedEventHandler(this.BtnPDetails_Click);
            
            #line default
            #line hidden
            return;
            case 26:
            this.btnChannel = ((System.Windows.Controls.Button)(target));
            
            #line 251 "..\..\..\..\View\Bill.xaml"
            this.btnChannel.Click += new System.Windows.RoutedEventHandler(this.btnChannel_Click);
            
            #line default
            #line hidden
            return;
            case 27:
            this.btnLogout = ((System.Windows.Controls.Button)(target));
            
            #line 256 "..\..\..\..\View\Bill.xaml"
            this.btnLogout.Click += new System.Windows.RoutedEventHandler(this.btnLogout_Click);
            
            #line default
            #line hidden
            return;
            case 28:
            this.lbl_LogOut = ((System.Windows.Controls.Label)(target));
            return;
            case 29:
            this.lbl_Addmit = ((System.Windows.Controls.Label)(target));
            return;
            case 30:
            this.lbl_Channel = ((System.Windows.Controls.Label)(target));
            return;
            case 31:
            this.lbl_ViewPatient = ((System.Windows.Controls.Label)(target));
            return;
            case 32:
            this.lbl_ViewStaff = ((System.Windows.Controls.Label)(target));
            return;
            case 33:
            this.lbl_Addmit_Copy = ((System.Windows.Controls.Label)(target));
            return;
            case 34:
            this.lbldischargedate = ((System.Windows.Controls.Label)(target));
            return;
            case 35:
            this.calander = ((System.Windows.Controls.Calendar)(target));
            return;
            }
            this._contentLoaded = true;
        }
    }
}

