#pragma checksum "..\..\..\..\View\InPatient.xaml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "9545EDFA97314DB812ADEB016DDE9ADCE1003BF7"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Controls.Ribbon;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;
using VistaLife.Resource;


namespace VistaLife.Resource {
    
    
    /// <summary>
    /// InPatient
    /// </summary>
    public partial class InPatient : System.Windows.Window, System.Windows.Markup.IComponentConnector {
        
        
        #line 65 "..\..\..\..\View\InPatient.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btnMinimize;
        
        #line default
        #line hidden
        
        
        #line 99 "..\..\..\..\View\InPatient.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btnMaximize;
        
        #line default
        #line hidden
        
        
        #line 132 "..\..\..\..\View\InPatient.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btnClose;
        
        #line default
        #line hidden
        
        
        #line 167 "..\..\..\..\View\InPatient.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.StackPanel loginStackPanel;
        
        #line default
        #line hidden
        
        
        #line 191 "..\..\..\..\View\InPatient.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox txtPATIENTname;
        
        #line default
        #line hidden
        
        
        #line 192 "..\..\..\..\View\InPatient.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox Title;
        
        #line default
        #line hidden
        
        
        #line 193 "..\..\..\..\View\InPatient.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox txtPage;
        
        #line default
        #line hidden
        
        
        #line 194 "..\..\..\..\View\InPatient.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox txtPAddress;
        
        #line default
        #line hidden
        
        
        #line 195 "..\..\..\..\View\InPatient.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox txtPbloodtype;
        
        #line default
        #line hidden
        
        
        #line 196 "..\..\..\..\View\InPatient.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox txtPadmittedDate;
        
        #line default
        #line hidden
        
        
        #line 197 "..\..\..\..\View\InPatient.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox txtGurdinName;
        
        #line default
        #line hidden
        
        
        #line 198 "..\..\..\..\View\InPatient.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox txtGurdianNIC;
        
        #line default
        #line hidden
        
        
        #line 201 "..\..\..\..\View\InPatient.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label lbl_Name;
        
        #line default
        #line hidden
        
        
        #line 202 "..\..\..\..\View\InPatient.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label lbl_Patient_sAge;
        
        #line default
        #line hidden
        
        
        #line 203 "..\..\..\..\View\InPatient.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label lbl_Patient_sAddress;
        
        #line default
        #line hidden
        
        
        #line 204 "..\..\..\..\View\InPatient.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label lbl_BloodType;
        
        #line default
        #line hidden
        
        
        #line 205 "..\..\..\..\View\InPatient.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label lbl_Gurdian_sName;
        
        #line default
        #line hidden
        
        
        #line 206 "..\..\..\..\View\InPatient.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label lbl_AdmittedDate;
        
        #line default
        #line hidden
        
        
        #line 207 "..\..\..\..\View\InPatient.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label lbl_Guradian_sNIC;
        
        #line default
        #line hidden
        
        
        #line 209 "..\..\..\..\View\InPatient.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btnSave;
        
        #line default
        #line hidden
        
        
        #line 210 "..\..\..\..\View\InPatient.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btnClear;
        
        #line default
        #line hidden
        
        
        #line 211 "..\..\..\..\View\InPatient.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btnUpdate;
        
        #line default
        #line hidden
        
        
        #line 216 "..\..\..\..\View\InPatient.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Grid Grid_Menu;
        
        #line default
        #line hidden
        
        
        #line 226 "..\..\..\..\View\InPatient.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button back;
        
        #line default
        #line hidden
        
        
        #line 232 "..\..\..\..\View\InPatient.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btnAddpatient;
        
        #line default
        #line hidden
        
        
        #line 237 "..\..\..\..\View\InPatient.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button BtnStaffDetails;
        
        #line default
        #line hidden
        
        
        #line 242 "..\..\..\..\View\InPatient.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button BtnPDetails;
        
        #line default
        #line hidden
        
        
        #line 247 "..\..\..\..\View\InPatient.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btnChannel;
        
        #line default
        #line hidden
        
        
        #line 252 "..\..\..\..\View\InPatient.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btnLogout;
        
        #line default
        #line hidden
        
        
        #line 256 "..\..\..\..\View\InPatient.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label lbl_LogOut;
        
        #line default
        #line hidden
        
        
        #line 258 "..\..\..\..\View\InPatient.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label lbl_Addmit;
        
        #line default
        #line hidden
        
        
        #line 259 "..\..\..\..\View\InPatient.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label lbl_Channel;
        
        #line default
        #line hidden
        
        
        #line 260 "..\..\..\..\View\InPatient.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label lbl_ViewPatient;
        
        #line default
        #line hidden
        
        
        #line 261 "..\..\..\..\View\InPatient.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label lbl_ViewStaff;
        
        #line default
        #line hidden
        
        
        #line 266 "..\..\..\..\View\InPatient.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label lbl_Addmit_Copy;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "8.0.0.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/VistaLife;component/view/inpatient.xaml", System.UriKind.Relative);
            
            #line 1 "..\..\..\..\View\InPatient.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "8.0.0.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            
            #line 14 "..\..\..\..\View\InPatient.xaml"
            ((VistaLife.Resource.InPatient)(target)).MouseDown += new System.Windows.Input.MouseButtonEventHandler(this.Window_MouseDown);
            
            #line default
            #line hidden
            return;
            case 2:
            this.btnMinimize = ((System.Windows.Controls.Button)(target));
            
            #line 74 "..\..\..\..\View\InPatient.xaml"
            this.btnMinimize.Click += new System.Windows.RoutedEventHandler(this.btnMinimize_Click);
            
            #line default
            #line hidden
            return;
            case 3:
            this.btnMaximize = ((System.Windows.Controls.Button)(target));
            
            #line 106 "..\..\..\..\View\InPatient.xaml"
            this.btnMaximize.Click += new System.Windows.RoutedEventHandler(this.btnMaximize_Click);
            
            #line default
            #line hidden
            return;
            case 4:
            this.btnClose = ((System.Windows.Controls.Button)(target));
            
            #line 141 "..\..\..\..\View\InPatient.xaml"
            this.btnClose.Click += new System.Windows.RoutedEventHandler(this.btnClose_Click);
            
            #line default
            #line hidden
            return;
            case 5:
            this.loginStackPanel = ((System.Windows.Controls.StackPanel)(target));
            return;
            case 6:
            this.txtPATIENTname = ((System.Windows.Controls.TextBox)(target));
            return;
            case 7:
            this.Title = ((System.Windows.Controls.TextBox)(target));
            return;
            case 8:
            this.txtPage = ((System.Windows.Controls.TextBox)(target));
            return;
            case 9:
            this.txtPAddress = ((System.Windows.Controls.TextBox)(target));
            return;
            case 10:
            this.txtPbloodtype = ((System.Windows.Controls.TextBox)(target));
            return;
            case 11:
            this.txtPadmittedDate = ((System.Windows.Controls.TextBox)(target));
            return;
            case 12:
            this.txtGurdinName = ((System.Windows.Controls.TextBox)(target));
            return;
            case 13:
            this.txtGurdianNIC = ((System.Windows.Controls.TextBox)(target));
            return;
            case 14:
            this.lbl_Name = ((System.Windows.Controls.Label)(target));
            return;
            case 15:
            this.lbl_Patient_sAge = ((System.Windows.Controls.Label)(target));
            return;
            case 16:
            this.lbl_Patient_sAddress = ((System.Windows.Controls.Label)(target));
            return;
            case 17:
            this.lbl_BloodType = ((System.Windows.Controls.Label)(target));
            return;
            case 18:
            this.lbl_Gurdian_sName = ((System.Windows.Controls.Label)(target));
            return;
            case 19:
            this.lbl_AdmittedDate = ((System.Windows.Controls.Label)(target));
            return;
            case 20:
            this.lbl_Guradian_sNIC = ((System.Windows.Controls.Label)(target));
            return;
            case 21:
            this.btnSave = ((System.Windows.Controls.Button)(target));
            return;
            case 22:
            this.btnClear = ((System.Windows.Controls.Button)(target));
            
            #line 210 "..\..\..\..\View\InPatient.xaml"
            this.btnClear.Click += new System.Windows.RoutedEventHandler(this.btnClear_Click);
            
            #line default
            #line hidden
            return;
            case 23:
            this.btnUpdate = ((System.Windows.Controls.Button)(target));
            return;
            case 24:
            this.Grid_Menu = ((System.Windows.Controls.Grid)(target));
            return;
            case 25:
            this.back = ((System.Windows.Controls.Button)(target));
            
            #line 226 "..\..\..\..\View\InPatient.xaml"
            this.back.Click += new System.Windows.RoutedEventHandler(this.back_Click);
            
            #line default
            #line hidden
            return;
            case 26:
            this.btnAddpatient = ((System.Windows.Controls.Button)(target));
            
            #line 232 "..\..\..\..\View\InPatient.xaml"
            this.btnAddpatient.Click += new System.Windows.RoutedEventHandler(this.btnAddpatient_Click);
            
            #line default
            #line hidden
            return;
            case 27:
            this.BtnStaffDetails = ((System.Windows.Controls.Button)(target));
            
            #line 237 "..\..\..\..\View\InPatient.xaml"
            this.BtnStaffDetails.Click += new System.Windows.RoutedEventHandler(this.BtnStaffDetails_Click);
            
            #line default
            #line hidden
            return;
            case 28:
            this.BtnPDetails = ((System.Windows.Controls.Button)(target));
            
            #line 242 "..\..\..\..\View\InPatient.xaml"
            this.BtnPDetails.Click += new System.Windows.RoutedEventHandler(this.BtnPDetails_Click);
            
            #line default
            #line hidden
            return;
            case 29:
            this.btnChannel = ((System.Windows.Controls.Button)(target));
            
            #line 247 "..\..\..\..\View\InPatient.xaml"
            this.btnChannel.Click += new System.Windows.RoutedEventHandler(this.btnChannel_Click);
            
            #line default
            #line hidden
            return;
            case 30:
            this.btnLogout = ((System.Windows.Controls.Button)(target));
            
            #line 252 "..\..\..\..\View\InPatient.xaml"
            this.btnLogout.Click += new System.Windows.RoutedEventHandler(this.btnLogout_Click);
            
            #line default
            #line hidden
            return;
            case 31:
            this.lbl_LogOut = ((System.Windows.Controls.Label)(target));
            return;
            case 32:
            this.lbl_Addmit = ((System.Windows.Controls.Label)(target));
            return;
            case 33:
            this.lbl_Channel = ((System.Windows.Controls.Label)(target));
            return;
            case 34:
            this.lbl_ViewPatient = ((System.Windows.Controls.Label)(target));
            return;
            case 35:
            this.lbl_ViewStaff = ((System.Windows.Controls.Label)(target));
            return;
            case 36:
            this.lbl_Addmit_Copy = ((System.Windows.Controls.Label)(target));
            return;
            }
            this._contentLoaded = true;
        }
    }
}

