#pragma checksum "..\..\..\..\View\Menue.xaml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "8D864EBCA28533A7372B63D90ED639E20613F7DD"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Controls.Ribbon;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;
using VistaLife.View;


namespace VistaLife.View {
    
    
    /// <summary>
    /// Menue
    /// </summary>
    public partial class Menue : System.Windows.Window, System.Windows.Markup.IComponentConnector {
        
        
        #line 65 "..\..\..\..\View\Menue.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btnMinimize;
        
        #line default
        #line hidden
        
        
        #line 99 "..\..\..\..\View\Menue.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btnMaximize;
        
        #line default
        #line hidden
        
        
        #line 132 "..\..\..\..\View\Menue.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btnClose;
        
        #line default
        #line hidden
        
        
        #line 167 "..\..\..\..\View\Menue.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.StackPanel loginStackPanel;
        
        #line default
        #line hidden
        
        
        #line 189 "..\..\..\..\View\Menue.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btn1AddmitPatient;
        
        #line default
        #line hidden
        
        
        #line 190 "..\..\..\..\View\Menue.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btn2ChanelDoctor;
        
        #line default
        #line hidden
        
        
        #line 191 "..\..\..\..\View\Menue.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btn3AddDoctor;
        
        #line default
        #line hidden
        
        
        #line 192 "..\..\..\..\View\Menue.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btn4AddNurse;
        
        #line default
        #line hidden
        
        
        #line 193 "..\..\..\..\View\Menue.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btn5ViewPatient;
        
        #line default
        #line hidden
        
        
        #line 194 "..\..\..\..\View\Menue.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btn6ViewStaff;
        
        #line default
        #line hidden
        
        
        #line 195 "..\..\..\..\View\Menue.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btn7Bill;
        
        #line default
        #line hidden
        
        
        #line 196 "..\..\..\..\View\Menue.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btn8DeleteRecord;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "8.0.1.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/VistaLife;V1.0.0.0;component/view/menue.xaml", System.UriKind.Relative);
            
            #line 1 "..\..\..\..\View\Menue.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "8.0.1.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            
            #line 14 "..\..\..\..\View\Menue.xaml"
            ((VistaLife.View.Menue)(target)).MouseDown += new System.Windows.Input.MouseButtonEventHandler(this.Window_MouseDown);
            
            #line default
            #line hidden
            return;
            case 2:
            this.btnMinimize = ((System.Windows.Controls.Button)(target));
            
            #line 74 "..\..\..\..\View\Menue.xaml"
            this.btnMinimize.Click += new System.Windows.RoutedEventHandler(this.btnMinimize_Click);
            
            #line default
            #line hidden
            return;
            case 3:
            this.btnMaximize = ((System.Windows.Controls.Button)(target));
            
            #line 106 "..\..\..\..\View\Menue.xaml"
            this.btnMaximize.Click += new System.Windows.RoutedEventHandler(this.btnMaximize_Click);
            
            #line default
            #line hidden
            return;
            case 4:
            this.btnClose = ((System.Windows.Controls.Button)(target));
            
            #line 141 "..\..\..\..\View\Menue.xaml"
            this.btnClose.Click += new System.Windows.RoutedEventHandler(this.btnClose_Click);
            
            #line default
            #line hidden
            return;
            case 5:
            this.loginStackPanel = ((System.Windows.Controls.StackPanel)(target));
            return;
            case 6:
            this.btn1AddmitPatient = ((System.Windows.Controls.Button)(target));
            
            #line 189 "..\..\..\..\View\Menue.xaml"
            this.btn1AddmitPatient.MouseEnter += new System.Windows.Input.MouseEventHandler(this.btn1AddmitPatient_MouseEnter);
            
            #line default
            #line hidden
            
            #line 189 "..\..\..\..\View\Menue.xaml"
            this.btn1AddmitPatient.MouseLeave += new System.Windows.Input.MouseEventHandler(this.btn1AddmitPatient_MouseLeave);
            
            #line default
            #line hidden
            
            #line 189 "..\..\..\..\View\Menue.xaml"
            this.btn1AddmitPatient.Click += new System.Windows.RoutedEventHandler(this.btn1AddmitPatient_Click_1);
            
            #line default
            #line hidden
            return;
            case 7:
            this.btn2ChanelDoctor = ((System.Windows.Controls.Button)(target));
            
            #line 190 "..\..\..\..\View\Menue.xaml"
            this.btn2ChanelDoctor.Click += new System.Windows.RoutedEventHandler(this.btn2ChanelDoctor_Click);
            
            #line default
            #line hidden
            
            #line 190 "..\..\..\..\View\Menue.xaml"
            this.btn2ChanelDoctor.MouseEnter += new System.Windows.Input.MouseEventHandler(this.btn2ChanelDoctor_MouseEnter);
            
            #line default
            #line hidden
            
            #line 190 "..\..\..\..\View\Menue.xaml"
            this.btn2ChanelDoctor.MouseLeave += new System.Windows.Input.MouseEventHandler(this.btn2ChanelDoctor_MouseLeave);
            
            #line default
            #line hidden
            return;
            case 8:
            this.btn3AddDoctor = ((System.Windows.Controls.Button)(target));
            
            #line 191 "..\..\..\..\View\Menue.xaml"
            this.btn3AddDoctor.Click += new System.Windows.RoutedEventHandler(this.btn3AddDoctor_Click);
            
            #line default
            #line hidden
            
            #line 191 "..\..\..\..\View\Menue.xaml"
            this.btn3AddDoctor.MouseEnter += new System.Windows.Input.MouseEventHandler(this.btn3AddDoctor_MouseEnter);
            
            #line default
            #line hidden
            
            #line 191 "..\..\..\..\View\Menue.xaml"
            this.btn3AddDoctor.MouseLeave += new System.Windows.Input.MouseEventHandler(this.btn3AddDoctor_MouseLeave);
            
            #line default
            #line hidden
            return;
            case 9:
            this.btn4AddNurse = ((System.Windows.Controls.Button)(target));
            
            #line 192 "..\..\..\..\View\Menue.xaml"
            this.btn4AddNurse.MouseEnter += new System.Windows.Input.MouseEventHandler(this.btn4AddNurse_MouseEnter);
            
            #line default
            #line hidden
            
            #line 192 "..\..\..\..\View\Menue.xaml"
            this.btn4AddNurse.MouseLeave += new System.Windows.Input.MouseEventHandler(this.btn4AddNurse_MouseLeave);
            
            #line default
            #line hidden
            
            #line 192 "..\..\..\..\View\Menue.xaml"
            this.btn4AddNurse.Click += new System.Windows.RoutedEventHandler(this.btn4AddNurse_Click);
            
            #line default
            #line hidden
            return;
            case 10:
            this.btn5ViewPatient = ((System.Windows.Controls.Button)(target));
            
            #line 193 "..\..\..\..\View\Menue.xaml"
            this.btn5ViewPatient.MouseEnter += new System.Windows.Input.MouseEventHandler(this.btn5ViewPatient_MouseEnter);
            
            #line default
            #line hidden
            
            #line 193 "..\..\..\..\View\Menue.xaml"
            this.btn5ViewPatient.MouseLeave += new System.Windows.Input.MouseEventHandler(this.btn5ViewPatient_MouseLeave);
            
            #line default
            #line hidden
            
            #line 193 "..\..\..\..\View\Menue.xaml"
            this.btn5ViewPatient.Click += new System.Windows.RoutedEventHandler(this.btn5ViewPatient_Click);
            
            #line default
            #line hidden
            return;
            case 11:
            this.btn6ViewStaff = ((System.Windows.Controls.Button)(target));
            
            #line 194 "..\..\..\..\View\Menue.xaml"
            this.btn6ViewStaff.MouseEnter += new System.Windows.Input.MouseEventHandler(this.btn6ViewStaff_MouseEnter);
            
            #line default
            #line hidden
            
            #line 194 "..\..\..\..\View\Menue.xaml"
            this.btn6ViewStaff.MouseLeave += new System.Windows.Input.MouseEventHandler(this.btn6ViewStaff_MouseLeave);
            
            #line default
            #line hidden
            
            #line 194 "..\..\..\..\View\Menue.xaml"
            this.btn6ViewStaff.Click += new System.Windows.RoutedEventHandler(this.btn6ViewStaff_Click);
            
            #line default
            #line hidden
            return;
            case 12:
            this.btn7Bill = ((System.Windows.Controls.Button)(target));
            
            #line 195 "..\..\..\..\View\Menue.xaml"
            this.btn7Bill.MouseEnter += new System.Windows.Input.MouseEventHandler(this.btn7Bill_MouseEnter);
            
            #line default
            #line hidden
            
            #line 195 "..\..\..\..\View\Menue.xaml"
            this.btn7Bill.MouseLeave += new System.Windows.Input.MouseEventHandler(this.btn7Bill_MouseLeave);
            
            #line default
            #line hidden
            
            #line 195 "..\..\..\..\View\Menue.xaml"
            this.btn7Bill.Click += new System.Windows.RoutedEventHandler(this.btn7Bill_Click);
            
            #line default
            #line hidden
            return;
            case 13:
            this.btn8DeleteRecord = ((System.Windows.Controls.Button)(target));
            
            #line 196 "..\..\..\..\View\Menue.xaml"
            this.btn8DeleteRecord.MouseEnter += new System.Windows.Input.MouseEventHandler(this.btn8DeleteRecord_MouseEnter);
            
            #line default
            #line hidden
            
            #line 196 "..\..\..\..\View\Menue.xaml"
            this.btn8DeleteRecord.MouseLeave += new System.Windows.Input.MouseEventHandler(this.btn8DeleteRecord_MouseLeave);
            
            #line default
            #line hidden
            
            #line 196 "..\..\..\..\View\Menue.xaml"
            this.btn8DeleteRecord.Click += new System.Windows.RoutedEventHandler(this.btn8DeleteRecord_Click);
            
            #line default
            #line hidden
            return;
            }
            this._contentLoaded = true;
        }
    }
}

