#pragma checksum "..\..\..\..\View\View Staff.xaml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "DAD2B1D33FEAADC2812E2D253B799EA950497013"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Controls.Ribbon;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;
using VistaLife.View;


namespace VistaLife.View {
    
    
    /// <summary>
    /// View_Staff
    /// </summary>
    public partial class View_Staff : System.Windows.Window, System.Windows.Markup.IComponentConnector {
        
        
        #line 65 "..\..\..\..\View\View Staff.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btnMinimize;
        
        #line default
        #line hidden
        
        
        #line 99 "..\..\..\..\View\View Staff.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btnMaximize;
        
        #line default
        #line hidden
        
        
        #line 132 "..\..\..\..\View\View Staff.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btnClose;
        
        #line default
        #line hidden
        
        
        #line 167 "..\..\..\..\View\View Staff.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.StackPanel loginStackPanel;
        
        #line default
        #line hidden
        
        
        #line 187 "..\..\..\..\View\View Staff.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox txtPName;
        
        #line default
        #line hidden
        
        
        #line 188 "..\..\..\..\View\View Staff.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox Title;
        
        #line default
        #line hidden
        
        
        #line 189 "..\..\..\..\View\View Staff.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ComboBox txtjob;
        
        #line default
        #line hidden
        
        
        #line 192 "..\..\..\..\View\View Staff.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label lbl_ID;
        
        #line default
        #line hidden
        
        
        #line 193 "..\..\..\..\View\View Staff.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label lbl_job;
        
        #line default
        #line hidden
        
        
        #line 196 "..\..\..\..\View\View Staff.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.DataGrid Dgridstaffdetails;
        
        #line default
        #line hidden
        
        
        #line 202 "..\..\..\..\View\View Staff.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btnShow;
        
        #line default
        #line hidden
        
        
        #line 203 "..\..\..\..\View\View Staff.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btnClear;
        
        #line default
        #line hidden
        
        
        #line 211 "..\..\..\..\View\View Staff.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Grid Grid_Menu;
        
        #line default
        #line hidden
        
        
        #line 221 "..\..\..\..\View\View Staff.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button back;
        
        #line default
        #line hidden
        
        
        #line 227 "..\..\..\..\View\View Staff.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btnAddpatient;
        
        #line default
        #line hidden
        
        
        #line 232 "..\..\..\..\View\View Staff.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button BtnStaffDetails;
        
        #line default
        #line hidden
        
        
        #line 237 "..\..\..\..\View\View Staff.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button BtnPDetails;
        
        #line default
        #line hidden
        
        
        #line 242 "..\..\..\..\View\View Staff.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btnChannel;
        
        #line default
        #line hidden
        
        
        #line 247 "..\..\..\..\View\View Staff.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btnLogout;
        
        #line default
        #line hidden
        
        
        #line 251 "..\..\..\..\View\View Staff.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label lbl_LogOut;
        
        #line default
        #line hidden
        
        
        #line 253 "..\..\..\..\View\View Staff.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label lbl_Addmit;
        
        #line default
        #line hidden
        
        
        #line 254 "..\..\..\..\View\View Staff.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label lbl_Channel;
        
        #line default
        #line hidden
        
        
        #line 255 "..\..\..\..\View\View Staff.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label lbl_ViewPatient;
        
        #line default
        #line hidden
        
        
        #line 256 "..\..\..\..\View\View Staff.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label lbl_ViewStaff;
        
        #line default
        #line hidden
        
        
        #line 258 "..\..\..\..\View\View Staff.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label lbl_Addmit_Copy;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "8.0.0.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/VistaLife;component/view/view%20staff.xaml", System.UriKind.Relative);
            
            #line 1 "..\..\..\..\View\View Staff.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "8.0.0.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            
            #line 14 "..\..\..\..\View\View Staff.xaml"
            ((VistaLife.View.View_Staff)(target)).MouseDown += new System.Windows.Input.MouseButtonEventHandler(this.Window_MouseDown);
            
            #line default
            #line hidden
            return;
            case 2:
            this.btnMinimize = ((System.Windows.Controls.Button)(target));
            
            #line 74 "..\..\..\..\View\View Staff.xaml"
            this.btnMinimize.Click += new System.Windows.RoutedEventHandler(this.btnMinimize_Click);
            
            #line default
            #line hidden
            return;
            case 3:
            this.btnMaximize = ((System.Windows.Controls.Button)(target));
            
            #line 106 "..\..\..\..\View\View Staff.xaml"
            this.btnMaximize.Click += new System.Windows.RoutedEventHandler(this.btnMaximize_Click);
            
            #line default
            #line hidden
            return;
            case 4:
            this.btnClose = ((System.Windows.Controls.Button)(target));
            
            #line 141 "..\..\..\..\View\View Staff.xaml"
            this.btnClose.Click += new System.Windows.RoutedEventHandler(this.btnClose_Click);
            
            #line default
            #line hidden
            return;
            case 5:
            this.loginStackPanel = ((System.Windows.Controls.StackPanel)(target));
            return;
            case 6:
            this.txtPName = ((System.Windows.Controls.TextBox)(target));
            return;
            case 7:
            this.Title = ((System.Windows.Controls.TextBox)(target));
            return;
            case 8:
            this.txtjob = ((System.Windows.Controls.ComboBox)(target));
            return;
            case 9:
            this.lbl_ID = ((System.Windows.Controls.Label)(target));
            return;
            case 10:
            this.lbl_job = ((System.Windows.Controls.Label)(target));
            return;
            case 11:
            this.Dgridstaffdetails = ((System.Windows.Controls.DataGrid)(target));
            return;
            case 12:
            this.btnShow = ((System.Windows.Controls.Button)(target));
            return;
            case 13:
            this.btnClear = ((System.Windows.Controls.Button)(target));
            
            #line 203 "..\..\..\..\View\View Staff.xaml"
            this.btnClear.Click += new System.Windows.RoutedEventHandler(this.btnClear_Click);
            
            #line default
            #line hidden
            return;
            case 14:
            this.Grid_Menu = ((System.Windows.Controls.Grid)(target));
            return;
            case 15:
            this.back = ((System.Windows.Controls.Button)(target));
            
            #line 221 "..\..\..\..\View\View Staff.xaml"
            this.back.Click += new System.Windows.RoutedEventHandler(this.back_Click);
            
            #line default
            #line hidden
            return;
            case 16:
            this.btnAddpatient = ((System.Windows.Controls.Button)(target));
            
            #line 227 "..\..\..\..\View\View Staff.xaml"
            this.btnAddpatient.Click += new System.Windows.RoutedEventHandler(this.btnAddpatient_Click);
            
            #line default
            #line hidden
            return;
            case 17:
            this.BtnStaffDetails = ((System.Windows.Controls.Button)(target));
            
            #line 232 "..\..\..\..\View\View Staff.xaml"
            this.BtnStaffDetails.Click += new System.Windows.RoutedEventHandler(this.BtnStaffDetails_Click);
            
            #line default
            #line hidden
            return;
            case 18:
            this.BtnPDetails = ((System.Windows.Controls.Button)(target));
            
            #line 237 "..\..\..\..\View\View Staff.xaml"
            this.BtnPDetails.Click += new System.Windows.RoutedEventHandler(this.BtnPDetails_Click);
            
            #line default
            #line hidden
            return;
            case 19:
            this.btnChannel = ((System.Windows.Controls.Button)(target));
            
            #line 242 "..\..\..\..\View\View Staff.xaml"
            this.btnChannel.Click += new System.Windows.RoutedEventHandler(this.btnChannel_Click);
            
            #line default
            #line hidden
            return;
            case 20:
            this.btnLogout = ((System.Windows.Controls.Button)(target));
            
            #line 247 "..\..\..\..\View\View Staff.xaml"
            this.btnLogout.Click += new System.Windows.RoutedEventHandler(this.btnLogout_Click);
            
            #line default
            #line hidden
            return;
            case 21:
            this.lbl_LogOut = ((System.Windows.Controls.Label)(target));
            return;
            case 22:
            this.lbl_Addmit = ((System.Windows.Controls.Label)(target));
            return;
            case 23:
            this.lbl_Channel = ((System.Windows.Controls.Label)(target));
            return;
            case 24:
            this.lbl_ViewPatient = ((System.Windows.Controls.Label)(target));
            return;
            case 25:
            this.lbl_ViewStaff = ((System.Windows.Controls.Label)(target));
            return;
            case 26:
            this.lbl_Addmit_Copy = ((System.Windows.Controls.Label)(target));
            return;
            }
            this._contentLoaded = true;
        }
    }
}

